// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuleHeritageHub.Infrastructure.DB;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModuleHeritageHub.Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250115122836_ChangedCVIDToNullable")]
    partial class ChangedCVIDToNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InfoList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.PageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PageId");

                    b.ToTable("PageVersions");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.PageVersionImage", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.HasKey("VersionId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("PageVersionImages");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.Page", b =>
                {
                    b.HasOne("ModuleHeritageHub.Domain.Model.PageVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId");

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.PageVersion", b =>
                {
                    b.HasOne("ModuleHeritageHub.Domain.Model.User", "Owner")
                        .WithMany("PageVersions")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModuleHeritageHub.Domain.Model.Page", "Page")
                        .WithMany("PageVersions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.PageVersionImage", b =>
                {
                    b.HasOne("ModuleHeritageHub.Domain.Model.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModuleHeritageHub.Domain.Model.PageVersion", "PageVersion")
                        .WithMany("Images")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("PageVersion");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.User", b =>
                {
                    b.HasOne("ModuleHeritageHub.Domain.Model.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.Page", b =>
                {
                    b.Navigation("PageVersions");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.PageVersion", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ModuleHeritageHub.Domain.Model.User", b =>
                {
                    b.Navigation("PageVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
